/*
* Copyright (c) Microsoft Corporation.  All rights reserved.
 *
 * documentdb_gateway_core/src/requests/request_type.rs
 *
 *-------------------------------------------------------------------------
 */

use std::{fmt, str::FromStr};

use crate::error::{DocumentDBError, ErrorCode, Result};

#[derive(PartialEq, Debug)]
pub enum RequestType {
    AbortTransaction,
    Aggregate,
    AppendOplogNote,
    ApplyOps,
    Authenticate,
    AuthSchemaUpgrade,
    AvailableQueryOptions,
    BalancerStart,
    BalancerStatus,
    BalancerStop,
    BuildInfo,
    CheckShardingIndex,
    CleanupOrphaned,
    Clone,
    CloneCatalogData,
    CloneCollection,
    CloneCollectionAsCapped,
    CloneCollectionOptionsFromPrimaryShard,
    CollMod,
    CollStats,
    CommitTransaction,
    Compact,
    ConfigsvrAddShard,
    ConfigsvrAddShardToZone,
    ConfigsvrBalancerStart,
    ConfigsvrBalancerStatus,
    ConfigsvrBalancerStop,
    ConfigsvrCommitChunkMerge,
    ConfigsvrCommitChunkMigration,
    ConfigsvrCommitChunkSplit,
    ConfigsvrCommitMovePrimary,
    ConfigsvrCreateCollection,
    ConfigsvrCreateDatabase,
    ConfigsvrDropCollection,
    ConfigsvrDropDatabase,
    ConfigsvrEnableSharding,
    ConfigsvrMoveChunk,
    ConfigsvrMovePrimary,
    ConfigsvrRemoveShard,
    ConfigsvrRemoveShardFromZone,
    ConfigsvrShardCollection,
    ConfigsvrUpdateZoneKeyRange,
    ConnectionStatus,
    ConnPoolStats,
    ConnPoolSync,
    ConvertToCapped,
    Copydb,
    Copydbgetnonce,
    Copydbsaslstart,
    Count,
    Create,
    CreateIndex,
    CreateIndexes,
    CreateRole,
    CreateUniqueOrCompoundIndexOnNestedPath,
    CreateUser,
    CurrentOp,
    CurrentOpCtx,
    CustomAction,
    DataSize,
    DbHash,
    DbStats,
    Delete,
    DeleteIndexes,
    DiagLogging,
    Distinct,
    DriverOIDTest,
    Drop,
    DropAllRolesFromDatabase,
    DropAllUsersFromDatabase,
    DropDatabase,
    DropIndexes,
    DropRole,
    DropUser,
    EnableSharding,
    EndSessions,
    Eval,
    Explain,
    Features,
    Filemd5,
    Find,
    FindAndModify,
    FlushDatabaseCacheUpdates,
    FlushRoutingTableCacheUpdates,
    Forceerror,
    Fsync,
    FsyncUnlock,
    GeoNear,
    GeoSearch,
    GetCmdLineOpts,
    GetDatabaseVersion,
    GetDefaultRWConcern,
    GetDiagnosticData,
    GetFreeMonitoringStatus,
    GetLastError,
    GetLastRequestStatistics,
    GetLog,
    GetMore,
    GetNextSessionMods,
    GetNonce,
    GetParameter,
    GetPrevError,
    GetShardMap,
    GetShardVersion,
    GetUserCacheGeneration,
    GrantPrivilegesToRole,
    GrantRolesToRole,
    GrantRolesToUser,
    Group,
    Handshake,
    Hello,
    HostInfo,
    Insert,
    InvalidateUserCache,
    Isdbgrid,
    IsMaster,
    IsSelf,
    KillAllSessions,
    KillAllSessionsByPattern,
    KillCursors,
    KillOp,
    KillSessions,
    ListCollections,
    ListCommands,
    ListDatabases,
    ListIndexes,
    ListShards,
    LockInfo,
    Logout,
    LogRotate,
    MapReduce,
    Mapreduceshardedfinish,
    MergeAuthzCollections,
    MergeChunks,
    MigrateClone,
    MoveChunk,
    MoveCollection,
    MovePrimary,
    ParallelCollectionScan,
    Ping,
    PlanCacheClear,
    PlanCacheClearFilters,
    PlanCacheListFilters,
    PlanCacheListPlans,
    PlanCacheListQueryShapes,
    PlanCacheSetFilter,
    PrepareTransaction,
    Profile,
    RecvChunkAbort,
    RecvChunkCommit,
    RecvChunkStart,
    RecvChunkStatus,
    RefreshSessions,
    RefreshSessionsInternal,
    ReIndex,
    RenameCollection,
    RepairCursor,
    RepairDatabase,
    ReplSetAbortPrimaryCatchUp,
    ReplSetDeclareElectionWinner,
    ReplSetElect,
    ReplSetFreeze,
    ReplSetFresh,
    ReplSetGetConfig,
    ReplSetGetRBID,
    ReplSetGetStatus,
    ReplSetHeartbeat,
    ReplSetInitiate,
    ReplSetMaintenance,
    ReplSetReconfig,
    ReplSetRequestVotes,
    ReplSetResizeOplog,
    ReplSetStepDown,
    ReplSetStepUp,
    ReplSetSyncFrom,
    ReplSetUpdatePosition,
    ResetError,
    ReshardCollection,
    ReSync,
    RevokePrivilegesFromRole,
    RevokeRolesFromRole,
    RevokeRolesFromUser,
    RolesInfo,
    SaslContinue,
    SaslStart,
    ServerStatus,
    SetFeatureCompatibilityVersion,
    SetFreeMonitoring,
    SetParameter,
    SetShardVersion,
    ShardCollection,
    ShardConnPoolStats,
    ShardingState,
    ShardsvrShardCollection,
    Shutdown,
    SplitChunk,
    SplitVector,
    StartSession,
    Top,
    Touch,
    TransferMods,
    UnsetSharding,
    UnshardCollection,
    Update,
    UpdateRole,
    UpdateUser,
    UsersInfo,
    Validate,
    WhatsMyUri,
    Writebacklisten,
}

impl RequestType {
    pub fn handle_with_auth(&self) -> bool {
        matches!(
            &self,
            RequestType::Logout | RequestType::SaslContinue | RequestType::SaslStart
        )
    }

    pub fn allowed_unauthorized(&self) -> bool {
        matches!(
            &self,
            RequestType::IsMaster | RequestType::Hello | RequestType::Ping | RequestType::BuildInfo
        )
    }

    pub fn to_command_str(&self) -> &'static str {
        match self {
            RequestType::AbortTransaction => "abortTransaction",
            RequestType::Aggregate => "aggregate",
            RequestType::AppendOplogNote => "appendOplogNote",
            RequestType::ApplyOps => "applyOps",
            RequestType::Authenticate => "authenticate",
            RequestType::AuthSchemaUpgrade => "authSchemaUpgrade",
            RequestType::AvailableQueryOptions => "availableQueryOptions",
            RequestType::BalancerStart => "balancerStart",
            RequestType::BalancerStatus => "balancerStatus",
            RequestType::BalancerStop => "balancerStop",
            RequestType::BuildInfo => "buildInfo",
            RequestType::CheckShardingIndex => "checkShardingIndex",
            RequestType::CleanupOrphaned => "cleanupOrphaned",
            RequestType::Clone => "clone",
            RequestType::CloneCatalogData => "_cloneCatalogData",
            RequestType::CloneCollection => "cloneCollection",
            RequestType::CloneCollectionAsCapped => "cloneCollectionAsCapped",
            RequestType::CloneCollectionOptionsFromPrimaryShard => {
                "_cloneCollectionOptionsFromPrimaryShard"
            }
            RequestType::CollMod => "collMod",
            RequestType::CollStats => "collStats",
            RequestType::CommitTransaction => "commitTransaction",
            RequestType::Compact => "compact",
            RequestType::ConfigsvrAddShard => "_configsvrAddShard",
            RequestType::ConfigsvrAddShardToZone => "_configsvrAddShardToZone",
            RequestType::ConfigsvrBalancerStart => "_configsvrBalancerStart",
            RequestType::ConfigsvrBalancerStatus => "_configsvrBalancerStatus",
            RequestType::ConfigsvrBalancerStop => "_configsvrBalancerStop",
            RequestType::ConfigsvrCommitChunkMerge => "_configsvrCommitChunkMerge",
            RequestType::ConfigsvrCommitChunkMigration => "_configsvrCommitChunkMigration",
            RequestType::ConfigsvrCommitChunkSplit => "_configsvrCommitChunkSplit",
            RequestType::ConfigsvrCommitMovePrimary => "_configsvrCommitMovePrimary",
            RequestType::ConfigsvrCreateCollection => "_configsvrCreateCollection",
            RequestType::ConfigsvrCreateDatabase => "_configsvrCreateDatabase",
            RequestType::ConfigsvrDropCollection => "_configsvrDropCollection",
            RequestType::ConfigsvrDropDatabase => "_configsvrDropDatabase",
            RequestType::ConfigsvrEnableSharding => "_configsvrEnableSharding",
            RequestType::ConfigsvrMoveChunk => "_configsvrMoveChunk",
            RequestType::ConfigsvrMovePrimary => "_configsvrMovePrimary",
            RequestType::ConfigsvrRemoveShard => "_configsvrRemoveShard",
            RequestType::ConfigsvrRemoveShardFromZone => "_configsvrRemoveShardFromZone",
            RequestType::ConfigsvrShardCollection => "_configsvrShardCollection",
            RequestType::ConfigsvrUpdateZoneKeyRange => "_configsvrUpdateZoneKeyRange",
            RequestType::ConnectionStatus => "connectionStatus",
            RequestType::ConnPoolStats => "connPoolStats",
            RequestType::ConnPoolSync => "connPoolSync",
            RequestType::ConvertToCapped => "convertToCapped",
            RequestType::Copydb => "copydb",
            RequestType::Copydbgetnonce => "copydbgetnonce",
            RequestType::Copydbsaslstart => "copydbsaslstart",
            RequestType::Count => "count",
            RequestType::Create => "create",
            RequestType::CreateIndex => "createIndex",
            RequestType::CreateIndexes => "createIndexes",
            RequestType::CreateRole => "createRole",
            RequestType::CreateUniqueOrCompoundIndexOnNestedPath => {
                "createUniqueOrCompoundIndexOnNestedPath"
            }
            RequestType::CreateUser => "createUser",
            RequestType::CurrentOp => "currentOp",
            RequestType::CurrentOpCtx => "currentOpCtx",
            RequestType::CustomAction => "customAction",
            RequestType::DataSize => "dataSize",
            RequestType::DbHash => "dbHash",
            RequestType::DbStats => "dbStats",
            RequestType::Delete => "delete",
            RequestType::DeleteIndexes => "deleteIndexes",
            RequestType::DiagLogging => "diagLogging",
            RequestType::Distinct => "distinct",
            RequestType::DriverOIDTest => "driverOIDTest",
            RequestType::Drop => "drop",
            RequestType::DropAllRolesFromDatabase => "dropAllRolesFromDatabase",
            RequestType::DropAllUsersFromDatabase => "dropAllUsersFromDatabase",
            RequestType::DropDatabase => "dropDatabase",
            RequestType::DropIndexes => "dropIndexes",
            RequestType::DropRole => "dropRole",
            RequestType::DropUser => "dropUser",
            RequestType::EnableSharding => "enableSharding",
            RequestType::EndSessions => "endSessions",
            RequestType::Eval => "eval",
            RequestType::Explain => "explain",
            RequestType::Features => "features",
            RequestType::Filemd5 => "filemd5",
            RequestType::Find => "find",
            RequestType::FindAndModify => "findAndModify",
            RequestType::FlushDatabaseCacheUpdates => "_flushDatabaseCacheUpdates",
            RequestType::FlushRoutingTableCacheUpdates => "_flushRoutingTableCacheUpdates",
            RequestType::Forceerror => "forceerror",
            RequestType::Fsync => "fsync",
            RequestType::FsyncUnlock => "fsyncUnlock",
            RequestType::GeoNear => "geoNear",
            RequestType::GeoSearch => "geoSearch",
            RequestType::GetCmdLineOpts => "getCmdLineOpts",
            RequestType::GetDatabaseVersion => "getDatabaseVersion",
            RequestType::GetDefaultRWConcern => "getDefaultRWConcern",
            RequestType::GetDiagnosticData => "getDiagnosticData",
            RequestType::GetFreeMonitoringStatus => "getFreeMonitoringStatus",
            RequestType::GetLastError => "getLastError",
            RequestType::GetLastRequestStatistics => "getLastRequestStatistics",
            RequestType::GetLog => "getLog",
            RequestType::GetMore => "getMore",
            RequestType::GetNextSessionMods => "_getNextSessionMods",
            RequestType::GetNonce => "getNonce",
            RequestType::GetParameter => "getParameter",
            RequestType::GetPrevError => "getPrevError",
            RequestType::GetShardMap => "getShardMap",
            RequestType::GetShardVersion => "getShardVersion",
            RequestType::GetUserCacheGeneration => "_getUserCacheGeneration",
            RequestType::GrantPrivilegesToRole => "grantPrivilegesToRole",
            RequestType::GrantRolesToRole => "grantRolesToRole",
            RequestType::GrantRolesToUser => "grantRolesToUser",
            RequestType::Group => "group",
            RequestType::Handshake => "handshake",
            RequestType::Hello => "hello",
            RequestType::HostInfo => "hostInfo",
            RequestType::Insert => "insert",
            RequestType::InvalidateUserCache => "invalidateUserCache",
            RequestType::Isdbgrid => "isdbgrid",
            RequestType::IsMaster => "isMaster",
            RequestType::IsSelf => "_isSelf",
            RequestType::KillAllSessions => "killAllSessions",
            RequestType::KillAllSessionsByPattern => "killAllSessionsByPattern",
            RequestType::KillCursors => "killCursors",
            RequestType::KillOp => "killOp",
            RequestType::KillSessions => "killSessions",
            RequestType::ListCollections => "listCollections",
            RequestType::ListCommands => "listCommands",
            RequestType::ListDatabases => "listDatabases",
            RequestType::ListIndexes => "listIndexes",
            RequestType::ListShards => "listShards",
            RequestType::LockInfo => "lockInfo",
            RequestType::Logout => "logout",
            RequestType::LogRotate => "logRotate",
            RequestType::MapReduce => "mapReduce",
            RequestType::Mapreduceshardedfinish => "mapreduce.shardedfinish",
            RequestType::MergeAuthzCollections => "_mergeAuthzCollections",
            RequestType::MergeChunks => "mergeChunks",
            RequestType::MigrateClone => "_migrateClone",
            RequestType::MoveChunk => "moveChunk",
            RequestType::MoveCollection => "moveCollection",
            RequestType::MovePrimary => "_movePrimary",
            RequestType::ParallelCollectionScan => "parallelCollectionScan",
            RequestType::Ping => "ping",
            RequestType::PlanCacheClear => "planCacheClear",
            RequestType::PlanCacheClearFilters => "planCacheClearFilters",
            RequestType::PlanCacheListFilters => "planCacheListFilters",
            RequestType::PlanCacheListPlans => "planCacheListPlans",
            RequestType::PlanCacheListQueryShapes => "planCacheListQueryShapes",
            RequestType::PlanCacheSetFilter => "planCacheSetFilter",
            RequestType::PrepareTransaction => "prepareTransaction",
            RequestType::Profile => "profile",
            RequestType::RecvChunkAbort => "_recvChunkAbort",
            RequestType::RecvChunkCommit => "_recvChunkCommit",
            RequestType::RecvChunkStart => "_recvChunkStart",
            RequestType::RecvChunkStatus => "_recvChunkStatus",
            RequestType::RefreshSessions => "refreshSessions",
            RequestType::RefreshSessionsInternal => "refreshSessionsInternal",
            RequestType::ReIndex => "reIndex",
            RequestType::RenameCollection => "renameCollection",
            RequestType::RepairCursor => "repairCursor",
            RequestType::RepairDatabase => "repairDatabase",
            RequestType::ReplSetAbortPrimaryCatchUp => "replSetAbortPrimaryCatchUp",
            RequestType::ReplSetDeclareElectionWinner => "replSetDeclareElectionWinner",
            RequestType::ReplSetElect => "replSetElect",
            RequestType::ReplSetFreeze => "replSetFreeze",
            RequestType::ReplSetFresh => "replSetFresh",
            RequestType::ReplSetGetConfig => "replSetGetConfig",
            RequestType::ReplSetGetRBID => "replSetGetRBID",
            RequestType::ReplSetGetStatus => "replSetGetStatus",
            RequestType::ReplSetHeartbeat => "replSetHeartbeat",
            RequestType::ReplSetInitiate => "replSetInitiate",
            RequestType::ReplSetMaintenance => "replSetMaintenance",
            RequestType::ReplSetReconfig => "replSetReconfig",
            RequestType::ReplSetRequestVotes => "replSetRequestVotes",
            RequestType::ReplSetResizeOplog => "replSetResizeOplog",
            RequestType::ReplSetStepDown => "replSetStepDown",
            RequestType::ReplSetStepUp => "replSetStepUp",
            RequestType::ReplSetSyncFrom => "replSetSyncFrom",
            RequestType::ReplSetUpdatePosition => "replSetUpdatePosition",
            RequestType::ResetError => "resetError",
            RequestType::ReshardCollection => "reshardCollection",
            RequestType::ReSync => "reSync",
            RequestType::RevokePrivilegesFromRole => "revokePrivilegesFromRole",
            RequestType::RevokeRolesFromRole => "revokeRolesFromRole",
            RequestType::RevokeRolesFromUser => "revokeRolesFromUser",
            RequestType::RolesInfo => "rolesInfo",
            RequestType::SaslContinue => "saslContinue",
            RequestType::SaslStart => "saslStart",
            RequestType::ServerStatus => "serverStatus",
            RequestType::SetFeatureCompatibilityVersion => "setFeatureCompatibilityVersion",
            RequestType::SetFreeMonitoring => "setFreeMonitoring",
            RequestType::SetParameter => "setParameter",
            RequestType::SetShardVersion => "setShardVersion",
            RequestType::ShardCollection => "shardCollection",
            RequestType::ShardConnPoolStats => "shardConnPoolStats",
            RequestType::ShardingState => "shardingState",
            RequestType::ShardsvrShardCollection => "_shardsvrShardCollection",
            RequestType::Shutdown => "shutdown",
            RequestType::SplitChunk => "splitChunk",
            RequestType::SplitVector => "splitVector",
            RequestType::StartSession => "startSession",
            RequestType::Top => "top",
            RequestType::Touch => "touch",
            RequestType::TransferMods => "_transferMods",
            RequestType::UnsetSharding => "unsetSharding",
            RequestType::UnshardCollection => "unshardCollection",
            RequestType::Update => "update",
            RequestType::UpdateRole => "updateRole",
            RequestType::UpdateUser => "updateUser",
            RequestType::UsersInfo => "usersInfo",
            RequestType::Validate => "validate",
            RequestType::WhatsMyUri => "whatsmyuri",
            RequestType::Writebacklisten => "writebacklisten",
        }
    }

    /// Returns `true` if this command is unconditionally blocked inside
    /// a multi-document transaction.
    pub fn is_blocked_in_transaction(&self) -> bool {
        matches!(
            self,
            RequestType::ReIndex
                | RequestType::CreateIndex
                | RequestType::CreateIndexes
                | RequestType::DropIndexes
                | RequestType::RenameCollection
                | RequestType::ListCollections
                | RequestType::Drop
                | RequestType::CurrentOp
                | RequestType::KillOp
        )
    }
}

impl FromStr for RequestType {
    type Err = DocumentDBError;

    fn from_str(cmd_name: &str) -> Result<Self> {
        match cmd_name {
            "abortTransaction" => Ok(RequestType::AbortTransaction),
            "aggregate" => Ok(RequestType::Aggregate),
            "appendOplogNote" => Ok(RequestType::AppendOplogNote),
            "applyOps" => Ok(RequestType::ApplyOps),
            "authenticate" => Ok(RequestType::Authenticate),
            "authSchemaUpgrade" => Ok(RequestType::AuthSchemaUpgrade),
            "availableQueryOptions" => Ok(RequestType::AvailableQueryOptions),
            "balancerStart" => Ok(RequestType::BalancerStart),
            "balancerStatus" => Ok(RequestType::BalancerStatus),
            "balancerStop" => Ok(RequestType::BalancerStop),
            "buildinfo" => Ok(RequestType::BuildInfo),
            "buildInfo" => Ok(RequestType::BuildInfo),
            "checkShardingIndex" => Ok(RequestType::CheckShardingIndex),
            "cleanupOrphaned" => Ok(RequestType::CleanupOrphaned),
            "clone" => Ok(RequestType::Clone),
            "_cloneCatalogData" => Ok(RequestType::CloneCatalogData),
            "cloneCollection" => Ok(RequestType::CloneCollection),
            "cloneCollectionAsCapped" => Ok(RequestType::CloneCollectionAsCapped),
            "_cloneCollectionOptionsFromPrimaryShard" => {
                Ok(RequestType::CloneCollectionOptionsFromPrimaryShard)
            }
            "collMod" => Ok(RequestType::CollMod),
            "collStats" => Ok(RequestType::CollStats),
            "commitTransaction" => Ok(RequestType::CommitTransaction),
            "compact" => Ok(RequestType::Compact),
            "_configsvrAddShard" => Ok(RequestType::ConfigsvrAddShard),
            "_configsvrAddShardToZone" => Ok(RequestType::ConfigsvrAddShardToZone),
            "_configsvrBalancerStart" => Ok(RequestType::ConfigsvrBalancerStart),
            "_configsvrBalancerStatus" => Ok(RequestType::ConfigsvrBalancerStatus),
            "_configsvrBalancerStop" => Ok(RequestType::ConfigsvrBalancerStop),
            "_configsvrCommitChunkMerge" => Ok(RequestType::ConfigsvrCommitChunkMerge),
            "_configsvrCommitChunkMigration" => Ok(RequestType::ConfigsvrCommitChunkMigration),
            "_configsvrCommitChunkSplit" => Ok(RequestType::ConfigsvrCommitChunkSplit),
            "_configsvrCommitMovePrimary" => Ok(RequestType::ConfigsvrCommitMovePrimary),
            "_configsvrCreateCollection" => Ok(RequestType::ConfigsvrCreateCollection),
            "_configsvrCreateDatabase" => Ok(RequestType::ConfigsvrCreateDatabase),
            "_configsvrDropCollection" => Ok(RequestType::ConfigsvrDropCollection),
            "_configsvrDropDatabase" => Ok(RequestType::ConfigsvrDropDatabase),
            "_configsvrEnableSharding" => Ok(RequestType::ConfigsvrEnableSharding),
            "_configsvrMoveChunk" => Ok(RequestType::ConfigsvrMoveChunk),
            "_configsvrMovePrimary" => Ok(RequestType::ConfigsvrMovePrimary),
            "_configsvrRemoveShard" => Ok(RequestType::ConfigsvrRemoveShard),
            "_configsvrRemoveShardFromZone" => Ok(RequestType::ConfigsvrRemoveShardFromZone),
            "_configsvrShardCollection" => Ok(RequestType::ConfigsvrShardCollection),
            "_configsvrUpdateZoneKeyRange" => Ok(RequestType::ConfigsvrUpdateZoneKeyRange),
            "connectionStatus" => Ok(RequestType::ConnectionStatus),
            "connPoolStats" => Ok(RequestType::ConnPoolStats),
            "connPoolSync" => Ok(RequestType::ConnPoolSync),
            "convertToCapped" => Ok(RequestType::ConvertToCapped),
            "copydb" => Ok(RequestType::Copydb),
            "copydbgetnonce" => Ok(RequestType::Copydbgetnonce),
            "copydbsaslstart" => Ok(RequestType::Copydbsaslstart),
            "count" => Ok(RequestType::Count),
            "create" => Ok(RequestType::Create),
            "createIndex" => Ok(RequestType::CreateIndex),
            "createIndexes" => Ok(RequestType::CreateIndexes),
            "createRole" => Ok(RequestType::CreateRole),
            "createUniqueOrCompoundIndexOnNestedPath" => {
                Ok(RequestType::CreateUniqueOrCompoundIndexOnNestedPath)
            }
            "createUser" => Ok(RequestType::CreateUser),
            "currentOp" => Ok(RequestType::CurrentOp),
            "currentOpCtx" => Ok(RequestType::CurrentOpCtx),
            "customAction" => Ok(RequestType::CustomAction),
            "dataSize" => Ok(RequestType::DataSize),
            "dbhash" => Ok(RequestType::DbHash),
            "dbHash" => Ok(RequestType::DbHash),
            "dbstats" => Ok(RequestType::DbStats),
            "dbStats" => Ok(RequestType::DbStats),
            "delete" => Ok(RequestType::Delete),
            "deleteIndexes" => Ok(RequestType::DeleteIndexes),
            "diagLogging" => Ok(RequestType::DiagLogging),
            "distinct" => Ok(RequestType::Distinct),
            "driverOIDTest" => Ok(RequestType::DriverOIDTest),
            "drop" => Ok(RequestType::Drop),
            "dropAllRolesFromDatabase" => Ok(RequestType::DropAllRolesFromDatabase),
            "dropAllUsersFromDatabase" => Ok(RequestType::DropAllUsersFromDatabase),
            "dropDatabase" => Ok(RequestType::DropDatabase),
            "dropIndexes" => Ok(RequestType::DropIndexes),
            "dropRole" => Ok(RequestType::DropRole),
            "dropUser" => Ok(RequestType::DropUser),
            "enableSharding" => Ok(RequestType::EnableSharding),
            "endSessions" => Ok(RequestType::EndSessions),
            "eval" => Ok(RequestType::Eval),
            "explain" => Ok(RequestType::Explain),
            "features" => Ok(RequestType::Features),
            "filemd5" => Ok(RequestType::Filemd5),
            "find" => Ok(RequestType::Find),
            "findandmodify" => Ok(RequestType::FindAndModify),
            "findAndModify" => Ok(RequestType::FindAndModify),
            "_flushDatabaseCacheUpdates" => Ok(RequestType::FlushDatabaseCacheUpdates),
            "_flushRoutingTableCacheUpdates" => Ok(RequestType::FlushRoutingTableCacheUpdates),
            "forceerror" => Ok(RequestType::Forceerror),
            "fsync" => Ok(RequestType::Fsync),
            "fsyncUnlock" => Ok(RequestType::FsyncUnlock),
            "geoNear" => Ok(RequestType::GeoNear),
            "geoSearch" => Ok(RequestType::GeoSearch),
            "getCmdLineOpts" => Ok(RequestType::GetCmdLineOpts),
            "getDatabaseVersion" => Ok(RequestType::GetDatabaseVersion),
            "getDefaultRWConcern" => Ok(RequestType::GetDefaultRWConcern),
            "getDiagnosticData" => Ok(RequestType::GetDiagnosticData),
            "getFreeMonitoringStatus" => Ok(RequestType::GetFreeMonitoringStatus),
            "getLastError" => Ok(RequestType::GetLastError),
            "getLastRequestStatistics" => Ok(RequestType::GetLastRequestStatistics),
            "getLog" => Ok(RequestType::GetLog),
            "getMore" => Ok(RequestType::GetMore),
            "_getNextSessionMods" => Ok(RequestType::GetNextSessionMods),
            "getNonce" => Ok(RequestType::GetNonce),
            "getParameter" => Ok(RequestType::GetParameter),
            "getPrevError" => Ok(RequestType::GetPrevError),
            "getShardMap" => Ok(RequestType::GetShardMap),
            "getShardVersion" => Ok(RequestType::GetShardVersion),
            "_getUserCacheGeneration" => Ok(RequestType::GetUserCacheGeneration),
            "grantPrivilegesToRole" => Ok(RequestType::GrantPrivilegesToRole),
            "grantRolesToRole" => Ok(RequestType::GrantRolesToRole),
            "grantRolesToUser" => Ok(RequestType::GrantRolesToUser),
            "group" => Ok(RequestType::Group),
            "handshake" => Ok(RequestType::Handshake),
            "hello" => Ok(RequestType::Hello),
            "hostInfo" => Ok(RequestType::HostInfo),
            "insert" => Ok(RequestType::Insert),
            "invalidateUserCache" => Ok(RequestType::InvalidateUserCache),
            "isdbgrid" => Ok(RequestType::Isdbgrid),
            "ismaster" => Ok(RequestType::IsMaster),
            "isMaster" => Ok(RequestType::IsMaster),
            "_isSelf" => Ok(RequestType::IsSelf),
            "killAllSessions" => Ok(RequestType::KillAllSessions),
            "killAllSessionsByPattern" => Ok(RequestType::KillAllSessionsByPattern),
            "killCursors" => Ok(RequestType::KillCursors),
            "killOp" => Ok(RequestType::KillOp),
            "killSessions" => Ok(RequestType::KillSessions),
            "listCollections" => Ok(RequestType::ListCollections),
            "listCommands" => Ok(RequestType::ListCommands),
            "listDatabases" => Ok(RequestType::ListDatabases),
            "listIndexes" => Ok(RequestType::ListIndexes),
            "listShards" => Ok(RequestType::ListShards),
            "lockInfo" => Ok(RequestType::LockInfo),
            "logout" => Ok(RequestType::Logout),
            "logRotate" => Ok(RequestType::LogRotate),
            "mapReduce" => Ok(RequestType::MapReduce),
            "mapreduce.shardedfinish" => Ok(RequestType::Mapreduceshardedfinish),
            "_mergeAuthzCollections" => Ok(RequestType::MergeAuthzCollections),
            "mergeChunks" => Ok(RequestType::MergeChunks),
            "_migrateClone" => Ok(RequestType::MigrateClone),
            "moveChunk" => Ok(RequestType::MoveChunk),
            "moveCollection" => Ok(RequestType::MoveCollection),
            "_movePrimary" => Ok(RequestType::MovePrimary),
            "parallelCollectionScan" => Ok(RequestType::ParallelCollectionScan),
            "ping" => Ok(RequestType::Ping),
            "planCacheClear" => Ok(RequestType::PlanCacheClear),
            "planCacheClearFilters" => Ok(RequestType::PlanCacheClearFilters),
            "planCacheListFilters" => Ok(RequestType::PlanCacheListFilters),
            "planCacheListPlans" => Ok(RequestType::PlanCacheListPlans),
            "planCacheListQueryShapes" => Ok(RequestType::PlanCacheListQueryShapes),
            "planCacheSetFilter" => Ok(RequestType::PlanCacheSetFilter),
            "prepareTransaction" => Ok(RequestType::PrepareTransaction),
            "profile" => Ok(RequestType::Profile),
            "_recvChunkAbort" => Ok(RequestType::RecvChunkAbort),
            "_recvChunkCommit" => Ok(RequestType::RecvChunkCommit),
            "_recvChunkStart" => Ok(RequestType::RecvChunkStart),
            "_recvChunkStatus" => Ok(RequestType::RecvChunkStatus),
            "refreshSessions" => Ok(RequestType::RefreshSessions),
            "refreshSessionsInternal" => Ok(RequestType::RefreshSessionsInternal),
            "reindex" => Ok(RequestType::ReIndex),
            "reIndex" => Ok(RequestType::ReIndex),
            "renameCollection" => Ok(RequestType::RenameCollection),
            "repairCursor" => Ok(RequestType::RepairCursor),
            "repairDatabase" => Ok(RequestType::RepairDatabase),
            "replSetAbortPrimaryCatchUp" => Ok(RequestType::ReplSetAbortPrimaryCatchUp),
            "replSetDeclareElectionWinner" => Ok(RequestType::ReplSetDeclareElectionWinner),
            "replSetElect" => Ok(RequestType::ReplSetElect),
            "replSetFreeze" => Ok(RequestType::ReplSetFreeze),
            "replSetFresh" => Ok(RequestType::ReplSetFresh),
            "replSetGetConfig" => Ok(RequestType::ReplSetGetConfig),
            "replSetGetRBID" => Ok(RequestType::ReplSetGetRBID),
            "replSetGetStatus" => Ok(RequestType::ReplSetGetStatus),
            "replSetHeartbeat" => Ok(RequestType::ReplSetHeartbeat),
            "replSetInitiate" => Ok(RequestType::ReplSetInitiate),
            "replSetMaintenance" => Ok(RequestType::ReplSetMaintenance),
            "replSetReconfig" => Ok(RequestType::ReplSetReconfig),
            "replSetRequestVotes" => Ok(RequestType::ReplSetRequestVotes),
            "replSetResizeOplog" => Ok(RequestType::ReplSetResizeOplog),
            "replSetStepDown" => Ok(RequestType::ReplSetStepDown),
            "replSetStepUp" => Ok(RequestType::ReplSetStepUp),
            "replSetSyncFrom" => Ok(RequestType::ReplSetSyncFrom),
            "replSetUpdatePosition" => Ok(RequestType::ReplSetUpdatePosition),
            "resetError" => Ok(RequestType::ResetError),
            "reshardCollection" => Ok(RequestType::ReshardCollection),
            "reSync" => Ok(RequestType::ReSync),
            "revokePrivilegesFromRole" => Ok(RequestType::RevokePrivilegesFromRole),
            "revokeRolesFromRole" => Ok(RequestType::RevokeRolesFromRole),
            "revokeRolesFromUser" => Ok(RequestType::RevokeRolesFromUser),
            "rolesInfo" => Ok(RequestType::RolesInfo),
            "saslContinue" => Ok(RequestType::SaslContinue),
            "saslStart" => Ok(RequestType::SaslStart),
            "serverStatus" => Ok(RequestType::ServerStatus),
            "setFeatureCompatibilityVersion" => Ok(RequestType::SetFeatureCompatibilityVersion),
            "setFreeMonitoring" => Ok(RequestType::SetFreeMonitoring),
            "setParameter" => Ok(RequestType::SetParameter),
            "setShardVersion" => Ok(RequestType::SetShardVersion),
            "shardCollection" => Ok(RequestType::ShardCollection),
            "shardConnPoolStats" => Ok(RequestType::ShardConnPoolStats),
            "shardingState" => Ok(RequestType::ShardingState),
            "_shardsvrShardCollection" => Ok(RequestType::ShardsvrShardCollection),
            "shutdown" => Ok(RequestType::Shutdown),
            "splitChunk" => Ok(RequestType::SplitChunk),
            "splitVector" => Ok(RequestType::SplitVector),
            "startSession" => Ok(RequestType::StartSession),
            "top" => Ok(RequestType::Top),
            "touch" => Ok(RequestType::Touch),
            "_transferMods" => Ok(RequestType::TransferMods),
            "unsetSharding" => Ok(RequestType::UnsetSharding),
            "unshardCollection" => Ok(RequestType::UnshardCollection),
            "update" => Ok(RequestType::Update),
            "updateRole" => Ok(RequestType::UpdateRole),
            "updateUser" => Ok(RequestType::UpdateUser),
            "usersInfo" => Ok(RequestType::UsersInfo),
            "validate" => Ok(RequestType::Validate),
            "whatsmyuri" => Ok(RequestType::WhatsMyUri),
            "writebacklisten" => Ok(RequestType::Writebacklisten),
            _ => Err(DocumentDBError::documentdb_error(
                ErrorCode::CommandNotFound,
                format!("Command '{cmd_name}' not found."),
            )),
        }
    }
}

impl fmt::Display for RequestType {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{self:?}")
    }
}
